<?php

namespace Database\Seeders;

use Illuminate\Support\Carbon;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = Carbon::now()->toDateTimeString();
        DB::table('users')->insert([
            [
                "id"            => 51,
                "name"          => "Administrator",
                "role_id"       => 1,
                "username"      => "admin",
                "email"         => "admin@mail.com",
                "plan_id"       => 3,
                "billing"       => "Manual - Credit Card",
                "is_status"     => 1,
                "avatar"        => "",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 1,
                "name"          => "Galen Slixby",
                "role_id"       => 5,
                "username"      => "gslixby0",
                "email"         => "gslixby0@abc.net.au",
                "plan_id"       => 3,
                "billing"       => "Manual - Credit Card",
                "is_status"     => 3,
                "avatar"        => "",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 2,
                "name"          => "Halsey Redmore",
                "role_id"       => 3,
                "username"      => "hredmore1",
                "email"         => "hredmore1@imgur.com",
                "plan_id"       => 4,
                "billing"       => "Manual - Paypal",
                "is_status"     => 1,
                "avatar"        => "10.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 3,
                "name"          => "Marjory Sicely",
                "role_id"       => 4,
                "username"      => "msicely2",
                "email"         => "msicely2@who.int",
                "plan_id"       => 3,
                "billing"       => "Auto Debit",
                "is_status"     => 2,
                "avatar"        => "1.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 4,
                "name"          => "Cyrill Risby",
                "role_id"       => 4,
                "username"      => "crisby3",
                "email"         => "crisby3@wordpress.com",
                "plan_id"       => 4,
                "billing"       => "Manual - Credit Card",
                "is_status"     => 3,
                "avatar"        => "9.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 5,
                "name"          => "Maggy Hurran",
                "role_id"       => 2,
                "username"      => "mhurran4",
                "email"         => "mhurran4@yahoo.co.jp",
                "plan_id"       => 3,
                "billing"       => "Auto Debit",
                "is_status"     => 1,
                "avatar"        => "10.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 6,
                "name"          => "Silvain Halstead",
                "role_id"       => 3,
                "username"      => "shalstead5",
                "email"         => "shalstead5@shinystat.com",
                "plan_id"       => 2,
                "billing"       => "Auto Debit",
                "is_status"     => 2,
                "avatar"        => "",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 7,
                "name"          => "Breena Gallemore",
                "role_id"       => 2,
                "username"      => "bgallemore6",
                "email"         => "bgallemore6@boston.com",
                "plan_id"       => 2,
                "billing"       => "Manual - Paypal",
                "is_status"     => 1,
                "avatar"        => "",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 8,
                "name"          => "Kathryne Liger",
                "role_id"       => 3,
                "username"      => "kliger7",
                "email"         => "kliger7@vinaora.com",
                "plan_id"       => 3,
                "billing"       => "Manual - Cash",
                "is_status"     => 1,
                "avatar"        => "9.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 9,
                "name"          => "Franz Scotfurth",
                "role_id"       => 2,
                "username"      => "fscotfurth8",
                "email"         => "fscotfurth8@dailymotion.com",
                "plan_id"       => 4,
                "billing"       => "Auto Debit",
                "is_status"     => 1,
                "avatar"        => "2.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 10,
                "name"          => "Jillene Bellany",
                "role_id"       => 4,
                "username"      => "jbellany9",
                "email"         => "jbellany9@kickstarter.com",
                "plan_id"       => 2,
                "billing"       => "Auto Debit",
                "is_status"     => 3,
                "avatar"        => "9.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 11,
                "name"          => "Jonah Wharlton",
                "role_id"       => 2,
                "username"      => "jwharltona",
                "email"         => "jwharltona@oakley.com",
                "plan_id"       => 4,
                "billing"       => "Manual - Paypal",
                "is_status"     => 3,
                "avatar"        => "4.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 12,
                "name"          => "Seth Hallam",
                "role_id"       => 2,
                "username"      => "shallamb",
                "email"         => "shallamb@hugedomains.com",
                "plan_id"       => 4,
                "billing"       => "Manual - Credit Card",
                "is_status"     => 1,
                "avatar"        => "5.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 13,
                "name"          => "Yoko Pottie",
                "role_id"       => 2,
                "username"      => "ypottiec",
                "email"         => "ypottiec@privacy.gov.au",
                "plan_id"       => 1,
                "billing"       => "Auto Debit",
                "is_status"     => 3,
                "avatar"        => "7.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 14,
                "name"          => "Maximilianus Krause",
                "role_id"       => 3,
                "username"      => "mkraused",
                "email"         => "mkraused@stanford.edu",
                "plan_id"       => 4,
                "billing"       => "Auto Debit",
                "is_status"     => 2,
                "avatar"        => "9.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 15,
                "name"          => "Zsazsa McCleverty",
                "role_id"       => 4,
                "username"      => "zmcclevertye",
                "email"         => "zmcclevertye@soundcloud.com",
                "plan_id"       => 3,
                "billing"       => "Auto Debit",
                "is_status"     => 2,
                "avatar"        => "2.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 16,
                "name"          => "Bentlee Emblin",
                "role_id"       => 3,
                "username"      => "bemblinf",
                "email"         => "bemblinf@wired.com",
                "plan_id"       => 2,
                "billing"       => "Auto Debit",
                "is_status"     => 2,
                "avatar"        => "6.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 17,
                "name"          => "Brockie Myles",
                "role_id"       => 4,
                "username"      => "bmylesg",
                "email"         => "bmylesg@amazon.com",
                "plan_id"       => 1,
                "billing"       => "Manual - Paypal",
                "is_status"     => 2,
                "avatar"        => "",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 18,
                "name"          => "Bertha Biner",
                "role_id"       => 5,
                "username"      => "bbinerh",
                "email"         => "bbinerh@mozilla.com",
                "plan_id"       => 4,
                "billing"       => "Manual - Cash",
                "is_status"     => 2,
                "avatar"        => "7.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 19,
                "name"          => "Travus Bruntjen",
                "role_id"       => 1,
                "username"      => "tbruntjeni",
                "email"         => "tbruntjeni@sitemeter.com",
                "plan_id"       => 3,
                "billing"       => "Manual - Cash",
                "is_status"     => 2,
                "avatar"        => "",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 20,
                "name"          => "Wesley Burland",
                "role_id"       => 5,
                "username"      => "wburlandj",
                "email"         => "wburlandj@uiuc.edu",
                "plan_id"       => 4,
                "billing"       => "Auto Debit",
                "is_status"     => 3,
                "avatar"        => "6.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 21,
                "name"          => "Stu Delamaine",
                "role_id"       => 3,
                "username"      => "sdelamainek",
                "email"         => "sdelamainek@who.int",
                "plan_id"       => 1,
                "billing"       => "Auto Debit",
                "is_status"     => 1,
                "avatar"        => "1.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 22,
                "name"          => "Jameson Lyster",
                "role_id"       => 5,
                "username"      => "jlysterl",
                "email"         => "jlysterl@guardian.co.uk",
                "plan_id"       => 2,
                "billing"       => "Auto Debit",
                "is_status"     => 3,
                "avatar"        => "8.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 23,
                "name"          => "Kare Skitterel",
                "role_id"       => 4,
                "username"      => "kskitterelm",
                "email"         => "kskitterelm@washingtonpost.com",
                "plan_id"       => 1,
                "billing"       => "Manual - Paypal",
                "is_status"     => 1,
                "avatar"        => "3.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 24,
                "name"          => "Cleavland Hatherleigh",
                "role_id"       => 1,
                "username"      => "chatherleighn",
                "email"         => "chatherleighn@washington.edu",
                "plan_id"       => 4,
                "billing"       => "Manual - Paypal",
                "is_status"     => 1,
                "avatar"        => "2.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 25,
                "name"          => "Adeline Micco",
                "role_id"       => 1,
                "username"      => "amiccoo",
                "email"         => "amiccoo@whitehouse.gov",
                "plan_id"       => 3,
                "billing"       => "Manual - Credit Card",
                "is_status"     => 1,
                "avatar"        => "",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 26,
                "name"          => "Hugh Hasson",
                "role_id"       => 1,
                "username"      => "hhassonp",
                "email"         => "hhassonp@bizjournals.com",
                "plan_id"       => 1,
                "billing"       => "Manual - Cash",
                "is_status"     => 3,
                "avatar"        => "4.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 27,
                "name"          => "Germain Jacombs",
                "role_id"       => 5,
                "username"      => "gjacombsq",
                "email"         => "gjacombsq@jigsy.com",
                "plan_id"       => 3,
                "billing"       => "Manual - Cash",
                "is_status"     => 2,
                "avatar"        => "10.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 28,
                "name"          => "Bree Kilday",
                "role_id"       => 4,
                "username"      => "bkildayr",
                "email"         => "bkildayr@mashable.com",
                "plan_id"       => 4,
                "billing"       => "Manual - Credit Card",
                "is_status"     => 2,
                "avatar"        => "",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 29,
                "name"          => "Candice Pinyon",
                "role_id"       => 4,
                "username"      => "cpinyons",
                "email"         => "cpinyons@behance.net",
                "plan_id"       => 4,
                "billing"       => "Auto Debit",
                "is_status"     => 2,
                "avatar"        => "7.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 30,
                "name"          => "Isabel Mallindine",
                "role_id"       => 2,
                "username"      => "imallindinet",
                "email"         => "imallindinet@shinystat.com",
                "plan_id"       => 4,
                "billing"       => "Manual - Credit Card",
                "is_status"     => 1,
                "avatar"        => "",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 31,
                "name"          => "Gwendolyn Meineken",
                "role_id"       => 1,
                "username"      => "gmeinekenu",
                "email"         => "gmeinekenu@hc360.com",
                "plan_id"       => 1,
                "billing"       => "Manual - Cash",
                "is_status"     => 1,
                "avatar"        => "1.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 32,
                "name"          => "Rafaellle Snowball",
                "role_id"       => 5,
                "username"      => "rsnowballv",
                "email"         => "rsnowballv@indiegogo.com",
                "plan_id"       => 1,
                "billing"       => "Manual - Paypal",
                "is_status"     => 1,
                "avatar"        => "5.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 33,
                "name"          => "Rochette Emer",
                "role_id"       => 1,
                "username"      => "remerw",
                "email"         => "remerw@blogtalkradio.com",
                "plan_id"       => 1,
                "billing"       => "Auto Debit",
                "is_status"     => 2,
                "avatar"        => "8.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 34,
                "name"          => "Ophelie Fibbens",
                "role_id"       => 2,
                "username"      => "ofibbensx",
                "email"         => "ofibbensx@booking.com",
                "plan_id"       => 2,
                "billing"       => "Manual - Cash",
                "is_status"     => 2,
                "avatar"        => "4.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 35,
                "name"          => "Stephen MacGilfoyle",
                "role_id"       => 4,
                "username"      => "smacgilfoyley",
                "email"         => "smacgilfoyley@bigcartel.com",
                "plan_id"       => 2,
                "billing"       => "Manual - Paypal",
                "is_status"     => 1,
                "avatar"        => "",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 36,
                "name"          => "Bradan Rosebotham",
                "role_id"       => 2,
                "username"      => "brosebothamz",
                "email"         => "brosebothamz@tripadvisor.com",
                "plan_id"       => 4,
                "billing"       => "Manual - Paypal",
                "is_status"     => 3,
                "avatar"        => "",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 37,
                "name"          => "Skip Hebblethwaite",
                "role_id"       => 1,
                "username"      => "shebblethwaite10",
                "email"         => "shebblethwaite10@arizona.edu",
                "plan_id"       => 2,
                "billing"       => "Manual - Cash",
                "is_status"     => 3,
                "avatar"        => "9.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 38,
                "name"          => "Moritz Piccard",
                "role_id"       => 4,
                "username"      => "mpiccard11",
                "email"         => "mpiccard11@vimeo.com",
                "plan_id"       => 3,
                "billing"       => "Manual - Credit Card",
                "is_status"     => 3,
                "avatar"        => "1.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 39,
                "name"          => "Tyne Widmore",
                "role_id"       => 2,
                "username"      => "twidmore12",
                "email"         => "twidmore12@bravesites.com",
                "plan_id"       => 4,
                "billing"       => "Manual - Cash",
                "is_status"     => 1,
                "avatar"        => "",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 40,
                "name"          => "Florenza Desporte",
                "role_id"       => 3,
                "username"      => "fdesporte13",
                "email"         => "fdesporte13@omniture.com",
                "plan_id"       => 2,
                "billing"       => "Manual - Cash",
                "is_status"     => 2,
                "avatar"        => "6.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 41,
                "name"          => "Edwina Baldetti",
                "role_id"       => 4,
                "username"      => "ebaldetti14",
                "email"         => "ebaldetti14@theguardian.com",
                "plan_id"       => 4,
                "billing"       => "Manual - Credit Card",
                "is_status"     => 1,
                "avatar"        => "",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 42,
                "name"          => "Benedetto Rossiter",
                "role_id"       => 5,
                "username"      => "brossiter15",
                "email"         => "brossiter15@craigslist.org",
                "plan_id"       => 4,
                "billing"       => "Manual - Cash",
                "is_status"     => 3,
                "avatar"        => "",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 43,
                "name"          => "Micaela McNirlan",
                "role_id"       => 1,
                "username"      => "mmcnirlan16",
                "email"         => "mmcnirlan16@hc360.com",
                "plan_id"       => 1,
                "billing"       => "Manual - Credit Card",
                "is_status"     => 3,
                "avatar"        => "",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 44,
                "name"          => "Vladamir Koschek",
                "role_id"       => 3,
                "username"      => "vkoschek17",
                "email"         => "vkoschek17@abc.net.au",
                "plan_id"       => 4,
                "billing"       => "Manual - Paypal",
                "is_status"     => 2,
                "avatar"        => "",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 45,
                "name"          => "Corrie Perot",
                "role_id"       => 2,
                "username"      => "cperot18",
                "email"         => "cperot18@goo.ne.jp",
                "plan_id"       => 4,
                "billing"       => "Manual - Paypal",
                "is_status"     => 1,
                "avatar"        => "3.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 46,
                "name"          => "Saunder Offner",
                "role_id"       => 4,
                "username"      => "soffner19",
                "email"         => "soffner19@mac.com",
                "plan_id"       => 3,
                "billing"       => "Auto Debit",
                "is_status"     => 1,
                "avatar"        => "",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 47,
                "name"          => "Karena Courtliff",
                "role_id"       => 1,
                "username"      => "kcourtliff1a",
                "email"         => "kcourtliff1a@bbc.co.uk",
                "plan_id"       => 1,
                "billing"       => "Manual - Paypal",
                "is_status"     => 2,
                "avatar"        => "1.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 48,
                "name"          => "Onfre Wind",
                "role_id"       => 1,
                "username"      => "owind1b",
                "email"         => "owind1b@yandex.ru",
                "plan_id"       => 1,
                "billing"       => "Manual - Paypal",
                "is_status"     => 1,
                "avatar"        => "",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 49,
                "name"          => "Paulie Durber",
                "role_id"       => 2,
                "username"      => "pdurber1c",
                "email"         => "pdurber1c@gov.uk",
                "plan_id"       => 4,
                "billing"       => "Manual - Cash",
                "is_status"     => 3,
                "avatar"        => "",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
            [
                "id"            => 50,
                "name"          => "Beverlie Krabbe",
                "role_id"       => 5,
                "username"      => "bkrabbe1d",
                "email"         => "bkrabbe1d@home.pl",
                "plan_id"       => 2,
                "billing"       => "Auto Debit",
                "is_status"     => 2,
                "avatar"        => "9.png",
                "company_id"    => 1,
                "password"      => bcrypt('admin'),
            ],
        ]);
        DB::statement("SELECT setval('users_id_seq', 100)");
    }
}
